namespace: siklu
name: eh
version: 1.1.1
readme: README.md
authors:
  - Dmitry Grinberg (Ceragon Networks)
description: Ansible Collection for Siklu EH millimeter-wave radio devices
license:
  - MIT
repository: https://github.com/siklu/ansible-collection
documentation: https://github.com/siklu/ansible-collection
issues: https://github.com/siklu/ansible-collection/issues

tags:
  - networking
  - infrastructure
  - siklu
  - ceragon
  - millimeterwave
  - wireless

dependencies:
  ansible.netcommon: ">=8.1.0"

build_ignore:
  - .gitignore
  - .git
  - .github
  - tests/output
  - '*.pyc'
  - '*.retry'
  - '*.tar.gz'
  - __pycache__
  - .pytest_cache
  - venv
  - .venv
  - .idea
  - .vscode
  - collections
